# Generated by Django 6.0.2 on 2026-03-16 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('brand_name', models.CharField(default='Upload Center', max_length=120)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('accent_color', models.CharField(default='#0ea5e9', max_length=20)),
                ('navigation_links', models.TextField(blank=True, help_text='One menu item per line as "Label|/path/".')),
            ],
            options={
                'verbose_name': 'Site theme settings',
                'verbose_name_plural': 'Site theme settings',
            },
        ),
        migrations.CreateModel(
            name='UploadCenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extensions', models.CharField(default='jpg,jpeg,png,gif,mp4,mp3,pdf', help_text='Comma separated file extensions without dot.', max_length=255)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum file size in megabytes.')),
            ],
            options={
                'verbose_name': 'Upload center settings',
                'verbose_name_plural': 'Upload center settings',
            },
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
